name: Create VPC Infrastructure

on:
  workflow_dispatch:
    inputs:
      vpc_name:
        description: 'VPC Name'
        required: true
        type: string
      cidr_block:
        description: 'VPC CIDR Block'
        required: true
        type: string
      region:
        description: 'AWS Region'
        required: true
        type: string

jobs:
  create-vpc-infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Inform starting of action
      uses: port-labs/port-github-action@v1
      with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Starting a GitHub worklfow to tag the AWS resource: ${{fromJson(inputs.port_context).entity.identifier}} ... ⛴️
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Create VPC
      id: create_vpc
      run: |
        VPC_ID=$(aws ec2 create-vpc --cidr-block ${{ github.event.inputs.cidr_block }} --query 'Vpc.VpcId' --output text)
        aws ec2 create-tags --resources $VPC_ID --tags Key=Name,Value=${{ github.event.inputs.vpc_name }}
        echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV
