name: Create VPC Infrastructure with Terraform

on:
  workflow_dispatch:
    inputs:
      vpc_name:
        description: 'VPC Name'
        required: true
        type: string
      cidr_block:
        description: 'VPC CIDR Block'
        required: true
        type: string
      region:
        description: 'AWS Region'
        required: true
        type: string

jobs:
  create-vpc-infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Change directory to module
      run: cd module
      working-directory: module

    - name: Terraform Init
      run: terraform init
      working-directory: module

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: module
      env:
        VPC_NAME: ${{ github.event.inputs.vpc_name }}
        CIDR_BLOCK: ${{ github.event.inputs.cidr_block }}
        AWS_REGION: ${{ github.event.inputs.region }}
